
CREATE PROCEDURE I_Permiso
    @ID INT OUTPUT
   ,@CODIGO VARCHAR(50)
   ,@NOMBRE VARCHAR(100)
   ,@DESCRIPCION VARCHAR(255)
   ,@MODULO VARCHAR(50)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Permiso
    (CODIGO ,NOMBRE ,DESCRIPCION ,MODULO)
    VALUES
    (@CODIGO ,@NOMBRE ,@DESCRIPCION ,@MODULO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Permiso
    @ID INT = NULL
   ,@CODIGO VARCHAR(50) = NULL
   ,@NOMBRE VARCHAR(100) = NULL
   ,@DESCRIPCION VARCHAR(255) = NULL
   ,@MODULO VARCHAR(50) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Permiso SET
    CODIGO = ISNULL(@CODIGO, CODIGO)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DESCRIPCION = ISNULL(@DESCRIPCION, DESCRIPCION)
   ,MODULO = ISNULL(@MODULO, MODULO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Permiso
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Permiso WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO