 
CREATE PROCEDURE I_Rol
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(50)
   ,@DESCRIPCION VARCHAR(255)
   ,@NIVELACCESO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Rol
    (NOMBRE ,DESCRIPCION ,NIVELACCESO)
    VALUES
    (@NOMBRE ,@DESCRIPCION ,@NIVELACCESO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Rol
    @ID INT = NULL
   ,@NOMBRE VARCHAR(50) = NULL
   ,@DESCRIPCION VARCHAR(255) = NULL
   ,@NIVELACCESO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Rol SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DESCRIPCION = ISNULL(@DESCRIPCION, DESCRIPCION)
   ,NIVELACCESO = ISNULL(@NIVELACCESO, NIVELACCESO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Rol
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Rol WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Permiso
    @ID INT OUTPUT
   ,@CODIGO VARCHAR(50)
   ,@NOMBRE VARCHAR(100)
   ,@DESCRIPCION VARCHAR(255)
   ,@MODULO VARCHAR(50)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Permiso
    (CODIGO ,NOMBRE ,DESCRIPCION ,MODULO)
    VALUES
    (@CODIGO ,@NOMBRE ,@DESCRIPCION ,@MODULO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Permiso
    @ID INT = NULL
   ,@CODIGO VARCHAR(50) = NULL
   ,@NOMBRE VARCHAR(100) = NULL
   ,@DESCRIPCION VARCHAR(255) = NULL
   ,@MODULO VARCHAR(50) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Permiso SET
    CODIGO = ISNULL(@CODIGO, CODIGO)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DESCRIPCION = ISNULL(@DESCRIPCION, DESCRIPCION)
   ,MODULO = ISNULL(@MODULO, MODULO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Permiso
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Permiso WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_RolPermiso
    @ID_ROL INT OUTPUT
   ,@ID_PERMISO INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO RolPermiso
 
    VALUES
 
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_RolPermiso
    @ID_ROL INT = NULL
   ,@ID_PERMISO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE RolPermiso SET
    WHERE ID_PERMISO = ID_PERMISO
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_RolPermiso
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM RolPermiso WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_UsuarioRol
    @ID_USUARIO INT OUTPUT
   ,@ID_ROL INT OUTPUT
   ,@FECHAASIGNACION DATETIME
   ,@ASIGNADOPOR INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO UsuarioRol
    (FECHAASIGNACION ,ASIGNADOPOR)
    VALUES
    (@FECHAASIGNACION ,@ASIGNADOPOR)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_UsuarioRol
    @ID_USUARIO INT = NULL
   ,@ID_ROL INT = NULL
   ,@FECHAASIGNACION DATETIME = NULL
   ,@ASIGNADOPOR INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE UsuarioRol SET
    FECHAASIGNACION = ISNULL(@FECHAASIGNACION, FECHAASIGNACION)
   ,ASIGNADOPOR = ISNULL(@ASIGNADOPOR, ASIGNADOPOR)
    WHERE ID_ROL = ID_ROL
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_UsuarioRol
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM UsuarioRol WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_UsuarioEntidad
    @ID INT OUTPUT
   ,@ID_USUARIO INT
   ,@TIPOENTIDAD VARCHAR(50)
   ,@ID_ENTIDAD INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO UsuarioEntidad
    (ID_USUARIO ,TIPOENTIDAD ,ID_ENTIDAD)
    VALUES
    (@ID_USUARIO ,@TIPOENTIDAD ,@ID_ENTIDAD)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_UsuarioEntidad
    @ID INT = NULL
   ,@ID_USUARIO INT = NULL
   ,@TIPOENTIDAD VARCHAR(50) = NULL
   ,@ID_ENTIDAD INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE UsuarioEntidad SET
    ID_USUARIO = ISNULL(@ID_USUARIO, ID_USUARIO)
   ,TIPOENTIDAD = ISNULL(@TIPOENTIDAD, TIPOENTIDAD)
   ,ID_ENTIDAD = ISNULL(@ID_ENTIDAD, ID_ENTIDAD)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_UsuarioEntidad
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM UsuarioEntidad WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_LogActividad
    @ID INT OUTPUT
   ,@ID_USUARIO INT
   ,@FECHAHORA DATETIME
   ,@ACCION VARCHAR(100)
   ,@DETALLES TEXT
   ,@DIRECCIONIP VARCHAR(45)
   ,@USERAGENT VARCHAR(255)
AS
BEGIN
  BEGIN TRY
    INSERT INTO LogActividad
    (ID_USUARIO ,FECHAHORA ,ACCION ,DETALLES ,DIRECCIONIP ,USERAGENT)
    VALUES
    (@ID_USUARIO ,@FECHAHORA ,@ACCION ,@DETALLES ,@DIRECCIONIP ,@USERAGENT)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_LogActividad
    @ID INT = NULL
   ,@ID_USUARIO INT = NULL
   ,@FECHAHORA DATETIME = NULL
   ,@ACCION VARCHAR(100) = NULL
   ,@DETALLES TEXT = NULL
   ,@DIRECCIONIP VARCHAR(45) = NULL
   ,@USERAGENT VARCHAR(255) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE LogActividad SET
    ID_USUARIO = ISNULL(@ID_USUARIO, ID_USUARIO)
   ,FECHAHORA = ISNULL(@FECHAHORA, FECHAHORA)
   ,ACCION = ISNULL(@ACCION, ACCION)
   ,DETALLES = ISNULL(@DETALLES, DETALLES)
   ,DIRECCIONIP = ISNULL(@DIRECCIONIP, DIRECCIONIP)
   ,USERAGENT = ISNULL(@USERAGENT, USERAGENT)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_LogActividad
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM LogActividad WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Institucion
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@DIRECCION VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Institucion
    (NOMBRE ,DIRECCION)
    VALUES
    (@NOMBRE ,@DIRECCION)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Institucion
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@DIRECCION VARCHAR(128) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Institucion SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,DIRECCION = ISNULL(@DIRECCION, DIRECCION)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Institucion
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Institucion WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Carrera
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@TITULO VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Carrera
    (NOMBRE ,TITULO)
    VALUES
    (@NOMBRE ,@TITULO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Carrera
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@TITULO VARCHAR(128) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Carrera SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,TITULO = ISNULL(@TITULO, TITULO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Carrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Carrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_InstitucionxCarrera
    @ID_INSTITUCION INT OUTPUT
   ,@ID_CARRERA INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO InstitucionxCarrera
 
    VALUES
 
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_InstitucionxCarrera
    @ID_INSTITUCION INT = NULL
   ,@ID_CARRERA INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE InstitucionxCarrera SET
    WHERE ID_CARRERA = ID_CARRERA
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_InstitucionxCarrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM InstitucionxCarrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Departamento
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@INTEGRANTES VARCHAR(128)
   ,@ID_CARRERA INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Departamento
    (NOMBRE ,INTEGRANTES ,ID_CARRERA)
    VALUES
    (@NOMBRE ,@INTEGRANTES ,@ID_CARRERA)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Departamento
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@INTEGRANTES VARCHAR(128) = NULL
   ,@ID_CARRERA INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Departamento SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,INTEGRANTES = ISNULL(@INTEGRANTES, INTEGRANTES)
   ,ID_CARRERA = ISNULL(@ID_CARRERA, ID_CARRERA)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Departamento
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Departamento WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Regimen
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Regimen
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Regimen
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Regimen SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Regimen
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Regimen WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Area
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Area
    (NOMBRE)
    VALUES
    (@NOMBRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Area
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Area SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Area
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Area WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_PlanEstudio
    @ID INT OUTPUT
   ,@AÑO DATETIME
   ,@NOMBRE VARCHAR(128)
   ,@AÑOFIN DATETIME
   ,@ID_CARRERA INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO PlanEstudio
    (AÑO ,NOMBRE ,AÑOFIN ,ID_CARRERA)
    VALUES
    (@AÑO ,@NOMBRE ,@AÑOFIN ,@ID_CARRERA)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_PlanEstudio
    @ID INT = NULL
   ,@AÑO DATETIME = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@AÑOFIN DATETIME = NULL
   ,@ID_CARRERA INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE PlanEstudio SET
    AÑO = ISNULL(@AÑO, AÑO)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,AÑOFIN = ISNULL(@AÑOFIN, AÑOFIN)
   ,ID_CARRERA = ISNULL(@ID_CARRERA, ID_CARRERA)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_PlanEstudio
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM PlanEstudio WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Cuatrimestre
    @ID INT OUTPUT
   ,@ID_PLAN INT
   ,@NRO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Cuatrimestre
    (ID_PLAN ,NRO)
    VALUES
    (@ID_PLAN ,@NRO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Cuatrimestre
    @ID INT = NULL
   ,@ID_PLAN INT = NULL
   ,@NRO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Cuatrimestre SET
    ID_PLAN = ISNULL(@ID_PLAN, ID_PLAN)
   ,NRO = ISNULL(@NRO, NRO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Cuatrimestre
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Cuatrimestre WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Asignatura
    @ID INT OUTPUT
   ,@HSEMANAL INT
   ,@NOMBRE VARCHAR(128)
   ,@HTOTALES INT
   ,@CREDITOS INT
   ,@ID_AREA INT
   ,@ID_REGIMEN INT
   ,@ID_DEPTO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Asignatura
    (HSEMANAL ,NOMBRE ,HTOTALES ,CREDITOS ,ID_AREA ,ID_REGIMEN ,ID_DEPTO)
    VALUES
    (@HSEMANAL ,@NOMBRE ,@HTOTALES ,@CREDITOS ,@ID_AREA ,@ID_REGIMEN ,@ID_DEPTO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Asignatura
    @ID INT = NULL
   ,@HSEMANAL INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@HTOTALES INT = NULL
   ,@CREDITOS INT = NULL
   ,@ID_AREA INT = NULL
   ,@ID_REGIMEN INT = NULL
   ,@ID_DEPTO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Asignatura SET
    HSEMANAL = ISNULL(@HSEMANAL, HSEMANAL)
   ,NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,HTOTALES = ISNULL(@HTOTALES, HTOTALES)
   ,CREDITOS = ISNULL(@CREDITOS, CREDITOS)
   ,ID_AREA = ISNULL(@ID_AREA, ID_AREA)
   ,ID_REGIMEN = ISNULL(@ID_REGIMEN, ID_REGIMEN)
   ,ID_DEPTO = ISNULL(@ID_DEPTO, ID_DEPTO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Asignatura
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Asignatura WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_AsignaturaxPlan
    @ID_PLAN INT OUTPUT
   ,@ID_ASIGNATURA INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO AsignaturaxPlan
 
    VALUES
 
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_AsignaturaxPlan
    @ID_PLAN INT = NULL
   ,@ID_ASIGNATURA INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE AsignaturaxPlan SET
    WHERE ID_ASIGNATURA = ID_ASIGNATURA
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_AsignaturaxPlan
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM AsignaturaxPlan WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_MateriasxCuatrimestre
    @ID_ASIGNATURA INT OUTPUT
   ,@ID_CUATRIMESTRE INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO MateriasxCuatrimestre
 
    VALUES
 
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_MateriasxCuatrimestre
    @ID_ASIGNATURA INT = NULL
   ,@ID_CUATRIMESTRE INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE MateriasxCuatrimestre SET
    WHERE ID_CUATRIMESTRE = ID_CUATRIMESTRE
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_MateriasxCuatrimestre
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM MateriasxCuatrimestre WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Correlativa
    @ID_ASIGNATURA INT OUTPUT
   ,@ID_CORRELATIVA INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Correlativa
 
    VALUES
 
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Correlativa
    @ID_ASIGNATURA INT = NULL
   ,@ID_CORRELATIVA INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Correlativa SET
    WHERE ID_CORRELATIVA = ID_CORRELATIVA
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Correlativa
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Correlativa WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Alumno
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@APELLIDO VARCHAR(128)
   ,@DNI VARCHAR(20)
   ,@FECHANACIMIENTO DATE
   ,@EMAIL VARCHAR(128)
   ,@TELEFONO VARCHAR(20)
   ,@DIRECCION VARCHAR(255)
   ,@FECHAINGRESO DATE
   ,@ESTADO VARCHAR(20)
AS
BEGIN
  BEGIN TRY
    INSERT INTO Alumno
    (NOMBRE ,APELLIDO ,DNI ,FECHANACIMIENTO ,EMAIL ,TELEFONO ,DIRECCION ,FECHAINGRESO ,ESTADO)
    VALUES
    (@NOMBRE ,@APELLIDO ,@DNI ,@FECHANACIMIENTO ,@EMAIL ,@TELEFONO ,@DIRECCION ,@FECHAINGRESO ,@ESTADO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Alumno
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@APELLIDO VARCHAR(128) = NULL
   ,@DNI VARCHAR(20) = NULL
   ,@FECHANACIMIENTO DATE = NULL
   ,@EMAIL VARCHAR(128) = NULL
   ,@TELEFONO VARCHAR(20) = NULL
   ,@DIRECCION VARCHAR(255) = NULL
   ,@FECHAINGRESO DATE = NULL
   ,@ESTADO VARCHAR(20) = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Alumno SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,APELLIDO = ISNULL(@APELLIDO, APELLIDO)
   ,DNI = ISNULL(@DNI, DNI)
   ,FECHANACIMIENTO = ISNULL(@FECHANACIMIENTO, FECHANACIMIENTO)
   ,EMAIL = ISNULL(@EMAIL, EMAIL)
   ,TELEFONO = ISNULL(@TELEFONO, TELEFONO)
   ,DIRECCION = ISNULL(@DIRECCION, DIRECCION)
   ,FECHAINGRESO = ISNULL(@FECHAINGRESO, FECHAINGRESO)
   ,ESTADO = ISNULL(@ESTADO, ESTADO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Alumno
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Alumno WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_AlumnoxCarrera
    @ID_ALUMNO INT OUTPUT
   ,@ID_CARRERA INT OUTPUT
   ,@FECHAINSCRIPCION DATE
AS
BEGIN
  BEGIN TRY
    INSERT INTO AlumnoxCarrera
    (FECHAINSCRIPCION)
    VALUES
    (@FECHAINSCRIPCION)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_AlumnoxCarrera
    @ID_ALUMNO INT = NULL
   ,@ID_CARRERA INT = NULL
   ,@FECHAINSCRIPCION DATE = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE AlumnoxCarrera SET
    FECHAINSCRIPCION = ISNULL(@FECHAINSCRIPCION, FECHAINSCRIPCION)
    WHERE ID_CARRERA = ID_CARRERA
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_AlumnoxCarrera
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM AlumnoxCarrera WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Profesor
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@APELLIDO VARCHAR(128)
   ,@DNI VARCHAR(20)
   ,@EMAIL VARCHAR(128)
   ,@TELEFONO VARCHAR(20)
   ,@TITULO VARCHAR(128)
   ,@ESPECIALIDAD VARCHAR(128)
   ,@TIPOCONTRATO VARCHAR(50)
   ,@FECHAINGRESO DATE
   ,@ID_DEPARTAMENTO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Profesor
    (NOMBRE ,APELLIDO ,DNI ,EMAIL ,TELEFONO ,TITULO ,ESPECIALIDAD ,TIPOCONTRATO ,FECHAINGRESO ,ID_DEPARTAMENTO)
    VALUES
    (@NOMBRE ,@APELLIDO ,@DNI ,@EMAIL ,@TELEFONO ,@TITULO ,@ESPECIALIDAD ,@TIPOCONTRATO ,@FECHAINGRESO ,@ID_DEPARTAMENTO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Profesor
    @ID INT = NULL
   ,@NOMBRE VARCHAR(128) = NULL
   ,@APELLIDO VARCHAR(128) = NULL
   ,@DNI VARCHAR(20) = NULL
   ,@EMAIL VARCHAR(128) = NULL
   ,@TELEFONO VARCHAR(20) = NULL
   ,@TITULO VARCHAR(128) = NULL
   ,@ESPECIALIDAD VARCHAR(128) = NULL
   ,@TIPOCONTRATO VARCHAR(50) = NULL
   ,@FECHAINGRESO DATE = NULL
   ,@ID_DEPARTAMENTO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Profesor SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,APELLIDO = ISNULL(@APELLIDO, APELLIDO)
   ,DNI = ISNULL(@DNI, DNI)
   ,EMAIL = ISNULL(@EMAIL, EMAIL)
   ,TELEFONO = ISNULL(@TELEFONO, TELEFONO)
   ,TITULO = ISNULL(@TITULO, TITULO)
   ,ESPECIALIDAD = ISNULL(@ESPECIALIDAD, ESPECIALIDAD)
   ,TIPOCONTRATO = ISNULL(@TIPOCONTRATO, TIPOCONTRATO)
   ,FECHAINGRESO = ISNULL(@FECHAINGRESO, FECHAINGRESO)
   ,ID_DEPARTAMENTO = ISNULL(@ID_DEPARTAMENTO, ID_DEPARTAMENTO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Profesor
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Profesor WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_ProfesorxAsignatura
    @ID_PROFESOR INT
   ,@ID_ASIGNATURA INT
   ,@ROL VARCHAR(50)
   ,@CUATRIMESTRE INT
   ,@AÑOACADEMICO INT OUTPUT
AS
BEGIN
  BEGIN TRY
    INSERT INTO ProfesorxAsignatura
    (ID_PROFESOR ,ID_ASIGNATURA ,ROL ,CUATRIMESTRE)
    VALUES
    (@ID_PROFESOR ,@ID_ASIGNATURA ,@ROL ,@CUATRIMESTRE)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_ProfesorxAsignatura
    @ID_PROFESOR INT = NULL
   ,@ID_ASIGNATURA INT = NULL
   ,@ROL VARCHAR(50) = NULL
   ,@CUATRIMESTRE INT = NULL
   ,@AÑOACADEMICO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE ProfesorxAsignatura SET
    ID_PROFESOR = ISNULL(@ID_PROFESOR, ID_PROFESOR)
   ,ID_ASIGNATURA = ISNULL(@ID_ASIGNATURA, ID_ASIGNATURA)
   ,ROL = ISNULL(@ROL, ROL)
   ,CUATRIMESTRE = ISNULL(@CUATRIMESTRE, CUATRIMESTRE)
    WHERE AÑOACADEMICO = AÑOACADEMICO
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_ProfesorxAsignatura
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM ProfesorxAsignatura WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Cursada
    @ID INT OUTPUT
   ,@ID_ALUMNO INT
   ,@ID_ASIGNATURA INT
   ,@ID_PLAN INT
   ,@AÑOACADEMICO INT
   ,@CUATRIMESTRE INT
   ,@ESTADO VARCHAR(20)
   ,@NOTAFINAL DECIMAL
AS
BEGIN
  BEGIN TRY
    INSERT INTO Cursada
    (ID_ALUMNO ,ID_ASIGNATURA ,ID_PLAN ,AÑOACADEMICO ,CUATRIMESTRE ,ESTADO ,NOTAFINAL)
    VALUES
    (@ID_ALUMNO ,@ID_ASIGNATURA ,@ID_PLAN ,@AÑOACADEMICO ,@CUATRIMESTRE ,@ESTADO ,@NOTAFINAL)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Cursada
    @ID INT = NULL
   ,@ID_ALUMNO INT = NULL
   ,@ID_ASIGNATURA INT = NULL
   ,@ID_PLAN INT = NULL
   ,@AÑOACADEMICO INT = NULL
   ,@CUATRIMESTRE INT = NULL
   ,@ESTADO VARCHAR(20) = NULL
   ,@NOTAFINAL DECIMAL = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Cursada SET
    ID_ALUMNO = ISNULL(@ID_ALUMNO, ID_ALUMNO)
   ,ID_ASIGNATURA = ISNULL(@ID_ASIGNATURA, ID_ASIGNATURA)
   ,ID_PLAN = ISNULL(@ID_PLAN, ID_PLAN)
   ,AÑOACADEMICO = ISNULL(@AÑOACADEMICO, AÑOACADEMICO)
   ,CUATRIMESTRE = ISNULL(@CUATRIMESTRE, CUATRIMESTRE)
   ,ESTADO = ISNULL(@ESTADO, ESTADO)
   ,NOTAFINAL = ISNULL(@NOTAFINAL, NOTAFINAL)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Cursada
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Cursada WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_ExamenFinal
    @ID INT OUTPUT
   ,@FECHA DATE
   ,@ID_ASIGNATURA INT
   ,@ID_PROFESOR INT
   ,@LLAMADO INT
AS
BEGIN
  BEGIN TRY
    INSERT INTO ExamenFinal
    (FECHA ,ID_ASIGNATURA ,ID_PROFESOR ,LLAMADO)
    VALUES
    (@FECHA ,@ID_ASIGNATURA ,@ID_PROFESOR ,@LLAMADO)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_ExamenFinal
    @ID INT = NULL
   ,@FECHA DATE = NULL
   ,@ID_ASIGNATURA INT = NULL
   ,@ID_PROFESOR INT = NULL
   ,@LLAMADO INT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE ExamenFinal SET
    FECHA = ISNULL(@FECHA, FECHA)
   ,ID_ASIGNATURA = ISNULL(@ID_ASIGNATURA, ID_ASIGNATURA)
   ,ID_PROFESOR = ISNULL(@ID_PROFESOR, ID_PROFESOR)
   ,LLAMADO = ISNULL(@LLAMADO, LLAMADO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_ExamenFinal
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM ExamenFinal WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_InscripcionExamen
    @ID INT OUTPUT
   ,@ID_ALUMNO INT
   ,@ID_EXAMENFINAL INT
   ,@ESTADO VARCHAR(20)
   ,@CALIFICACION DECIMAL
   ,@OBSERVACIONES TEXT
AS
BEGIN
  BEGIN TRY
    INSERT INTO InscripcionExamen
    (ID_ALUMNO ,ID_EXAMENFINAL ,ESTADO ,CALIFICACION ,OBSERVACIONES)
    VALUES
    (@ID_ALUMNO ,@ID_EXAMENFINAL ,@ESTADO ,@CALIFICACION ,@OBSERVACIONES)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_InscripcionExamen
    @ID INT = NULL
   ,@ID_ALUMNO INT = NULL
   ,@ID_EXAMENFINAL INT = NULL
   ,@ESTADO VARCHAR(20) = NULL
   ,@CALIFICACION DECIMAL = NULL
   ,@OBSERVACIONES TEXT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE InscripcionExamen SET
    ID_ALUMNO = ISNULL(@ID_ALUMNO, ID_ALUMNO)
   ,ID_EXAMENFINAL = ISNULL(@ID_EXAMENFINAL, ID_EXAMENFINAL)
   ,ESTADO = ISNULL(@ESTADO, ESTADO)
   ,CALIFICACION = ISNULL(@CALIFICACION, CALIFICACION)
   ,OBSERVACIONES = ISNULL(@OBSERVACIONES, OBSERVACIONES)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_InscripcionExamen
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM InscripcionExamen WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE I_Usuario
    @ID INT OUTPUT
   ,@USERNAME VARCHAR(50)
   ,@PASSWORDHASH VARCHAR(255)
   ,@EMAIL VARCHAR(128)
   ,@FECHACREACION DATETIME
   ,@ULTIMOACCESO DATETIME
   ,@ESTADO VARCHAR(20)
   ,@INTENTOSFALLIDOS INT
   ,@TOKENRECUPERACION VARCHAR(255)
   ,@EXPIRACIONTOKEN DATETIME
   ,@REQUIERECAMBIOPASSWORD BIT
AS
BEGIN
  BEGIN TRY
    INSERT INTO Usuario
    (USERNAME ,PASSWORDHASH ,EMAIL ,FECHACREACION ,ULTIMOACCESO ,ESTADO ,INTENTOSFALLIDOS ,TOKENRECUPERACION ,EXPIRACIONTOKEN ,REQUIERECAMBIOPASSWORD)
    VALUES
    (@USERNAME ,@PASSWORDHASH ,@EMAIL ,@FECHACREACION ,@ULTIMOACCESO ,@ESTADO ,@INTENTOSFALLIDOS ,@TOKENRECUPERACION ,@EXPIRACIONTOKEN ,@REQUIERECAMBIOPASSWORD)
     SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
CREATE PROCEDURE U_Usuario
    @ID INT = NULL
   ,@USERNAME VARCHAR(50) = NULL
   ,@PASSWORDHASH VARCHAR(255) = NULL
   ,@EMAIL VARCHAR(128) = NULL
   ,@FECHACREACION DATETIME = NULL
   ,@ULTIMOACCESO DATETIME = NULL
   ,@ESTADO VARCHAR(20) = NULL
   ,@INTENTOSFALLIDOS INT = NULL
   ,@TOKENRECUPERACION VARCHAR(255) = NULL
   ,@EXPIRACIONTOKEN DATETIME = NULL
   ,@REQUIERECAMBIOPASSWORD BIT = NULL
AS
BEGIN
  BEGIN TRY
    UPDATE Usuario SET
    USERNAME = ISNULL(@USERNAME, USERNAME)
   ,PASSWORDHASH = ISNULL(@PASSWORDHASH, PASSWORDHASH)
   ,EMAIL = ISNULL(@EMAIL, EMAIL)
   ,FECHACREACION = ISNULL(@FECHACREACION, FECHACREACION)
   ,ULTIMOACCESO = ISNULL(@ULTIMOACCESO, ULTIMOACCESO)
   ,ESTADO = ISNULL(@ESTADO, ESTADO)
   ,INTENTOSFALLIDOS = ISNULL(@INTENTOSFALLIDOS, INTENTOSFALLIDOS)
   ,TOKENRECUPERACION = ISNULL(@TOKENRECUPERACION, TOKENRECUPERACION)
   ,EXPIRACIONTOKEN = ISNULL(@EXPIRACIONTOKEN, EXPIRACIONTOKEN)
   ,REQUIERECAMBIOPASSWORD = ISNULL(@REQUIERECAMBIOPASSWORD, REQUIERECAMBIOPASSWORD)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
 
 
CREATE PROCEDURE D_Usuario
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM Usuario WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo
  END CATCH
END;
GO
